---
- name: install packages
  package:
    name: 
      - java
      - logstash
    state: present

- name: copy logstash pipeline conf
  copy:
    src: "{{ role_path }}/files/logstash/pipelines.yml"
    dest: /etc/logstash/
  notify:
    - restart logstash

- name: copy logstash conf.d
  synchronize:
    src: "{{ role_path }}/files/logstash/conf.d"
    dest: /etc/logstash/
    recursive: yes
    delete: yes
    archive: no
  notify:
    - restart logstash
