metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "kibana-microservices.servers:80"

output.elasticsearch:
  hosts: ["elastic-microservices.vs:9200"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
