# MICROSERVICES LOGS

# Essa conf eh com base em pipeline-to-pipeline:
# https://www.elastic.co/guide/en/logstash/master/pipeline-to-pipeline.html

# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: main
  queue.type: persisted
  queue.page_capacity: 64mb
  queue.drain: false
  queue.max_events: 0
  queue.max_bytes: 512mb
  path.queue: /var/lib/logstash/queue
  path.config: "/etc/logstash/conf.d/main.conf"
  pipeline.workers: 1

- pipeline.id: microservices
  path.config: "/etc/logstash/conf.d/microservices.conf"
  pipeline.workers: 1
